In [2]:
import sys
import numpy as np

In [3]:
array_id = np.array([4.5, 3 ])
type(array_id)

numpy.ndarray

In [4]:
array_id.ndim

1

In [5]:
array_id.shape

(2,)

In [6]:
matriz = np.array([
    [1,2,3],
    [4,5,6]
])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matriz.ndim

2

In [8]:
matriz.shape

(2, 3)

In [9]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.ones((2))

array([1., 1.])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random((2,3))

array([[0.75402158, 0.7433658 , 0.55851273],
       [0.98416888, 0.65710748, 0.98860083]])

In [13]:
!cat np_text.txt

1,2,3
43,2,3
34,1,1
0,1,1

In [14]:
np_text = np.genfromtxt("np_text.txt", delimiter=',')
np_text

array([[ 1.,  2.,  3.],
       [43.,  2.,  3.],
       [34.,  1.,  1.],
       [ 0.,  1.,  1.]])

In [15]:
lista_2d = [[1,2,3], [4,5,6]]

array_2d = np.array([[1,2,3], [4,5,6]])

In [16]:
sys.getsizeof(lista_2d)


72

In [17]:
sys.getsizeof(array_2d)

168

In [18]:
big_lista = list(range(100000))
big_array = np.array(range(100000))

In [20]:
sys.getsizeof(big_lista)

800056

In [21]:
sys.getsizeof(big_array)

800104

In [26]:
%%timeit

sum(range(1000000))

17 ms ± 146 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
%%timeit

np.sum(np.arange(1000000))

2.18 ms ± 48.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
np.array([1.0, 5.4, ]).dtype

dtype('float64')

In [31]:
np.float64

numpy.float64

In [33]:
np.array([1.0, 2.0, "patata"])

array(['1.0', '2.0', 'patata'], dtype='<U32')

In [36]:
%%timeit

["{}".format(i) for i in range(1000000)]

240 ms ± 4.64 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [38]:
f = np.vectorize(lambda x: "{}".format(x))

In [41]:
%%timeit 

f(np.arange(1000000))

453 ms ± 5.98 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
matriz_34 = np.array([
    [1,2,3,4], [5,6,7,8], [9,10,11,12]
])

matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
matriz_34[0]

array([1, 2, 3, 4])

In [47]:
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
matriz_34[:,1]

array([ 2,  6, 10])

In [51]:
matriz_34[1,1]

6