Importa numpy

In [2]:
import numpy as np

crea un numpy array que tenga la siguente estructura

```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

llamalo `array`

In [2]:
array = np.array([
    [1, 6, 11],
    [2, 7, 12],
    [3, 8, 13],
    [4, 9, 14],
    [5, 10, 15]
])

averigua la forma del array

In [4]:
array.shape

(5, 3)

Selecciona la segunda columna del array

In [10]:
array[:,1]

array([ 6,  7,  8,  9, 10])

 Crea un vector con los valores del 15 al 55, llamalo array2
    
*pista: usa np.arange*

In [9]:
array2 = np.arange(15,56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

asigna el valor 23 a la quinta posicion del array2

In [10]:
array2[4] = 23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

convierte array2 del revés (es decir `[55,54,....,15]`

In [11]:
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

Crea una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares de array2, llamala `matriz_diag`

*pista: usa np.diag*

In [12]:
matriz_diag = np.diag( array2[1::2][:5] )
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

Imprime el numero de dimensiones de `matriz_diag`

In [48]:
matriz_diag.ndim

2

Crea una matriz con números aleatorios de tamaño 5x3 (4 filas por 3 columnas), llamala `matriz`

In [3]:
matriz = np.random.random((5,3))
matriz

array([[0.88018775, 0.47662631, 0.61925895],
       [0.45794313, 0.86474545, 0.05134863],
       [0.46091982, 0.17188288, 0.47439914],
       [0.13576994, 0.55908325, 0.12037205],
       [0.09591133, 0.33805712, 0.02202748]])

multiplica `matriz` por `matriz_diag`

In [4]:
matriz @ matriz_diag

NameError: name 'matriz_diag' is not defined

In [13]:
matriz.T @ matriz_diag

array([[14.08300393,  8.24297641,  9.21839632,  2.98693867,  2.30187185],
       [ 7.62602098, 15.56541815,  3.43765752, 12.29983142,  8.11337086],
       [ 9.90814322,  0.92427531,  9.48798278,  2.64818499,  0.52865959]])